# Generated by Django 2.2 on 2019-05-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hypertext_search', '0002_webpage_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='rank',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
