# Generated by Django 2.2 on 2019-05-11 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hypertext_search', '0003_auto_20190511_1604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webpage',
            old_name='rank',
            new_name='web_rank',
        ),
    ]
